version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net-backend
  order-service:
    image: mroger/pag-order:0.0.1-SNAPSHOT
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:33306/order?useSSL=false&serverTimezone=America/Sao_Paulo'
    ports:
      - '9090:9090'
    expose:
      - '9090'
    depends_on:
      - db
    networks:
      - net-backend
volumes:
    mysql_data:
        driver: local

networks:
  net-backend:
