version: '3.3'
services:
  mysql:
    container_name: pag-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'order'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/scripts/create_database.sql:/docker-entrypoint-initdb.d/init.sql:ro
  order-service:
    container_name: pag-order-service
    image: mroger/pag-order:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/order?useSSL=false&serverTimezone=America/Sao_Paulo'
    ports:
      - '9090:9090'
    depends_on:
      - 'mysql'
    command: ["/wait-for-it.sh", "-t", "45", "mysql:3306", "--", "java","-cp","app:app/lib/*","br.com.pag.service.order.OrderApplication"]
volumes:
    mysql_data:
        driver: local
