management:
  server:
    servlet:
      context-path: /actuator
  endpoints:
    web:
      exposure:
        include: "beans,env,info,metrics,health"

server:
  port: 9090
  servlet:
    context-path: /pag-order

spring:
  application:
    name: pag-order
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    time-zone: "America/Sao_Paulo"
  datasource:
    url: jdbc:mysql://localhost:33306/order
    username: root
    password: password
    validation-query: SELECT 1 FROM dual
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 500
        rewriteBatchedStatements: true
        idle-timeout: 10000
  jpa:
    show_sql: false
  messages:
    fallback-to-system-locale: false
  sleuth:
    log:
      slf4j:
        enabled: false
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    baseUrl: http://localhost:9411/

logging:
  config:
    classpath: log4j2.yml
